config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'

  resources :photos do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  
  before_validation :store_user_password
  before_save :store_image_size

  private

  def store_user_password
    self.password = ENV['APP_PASSWORD']
  end

  def store_image_size
    photo_size = FastImage.size(url)
    self.width = photo_size[0]
    self.height = photo_size[1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    redirect_to root_path if @photo.save
  end

  def destroy
    @photo = Photo.find(params[:id]).try(:authenticate, params[:password])

    @photo&.destroy

    redirect_to root_path
  end

  def search
    @photos = Photo.all.where('label LIKE :query', query: "%#{params[:query]}%")

    render :index
  end

  private

  def photo_params
    params.require(:photo).permit(:label, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Unsplash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <main class="mx-24">
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_add_modal.html.erb
<div id="modal-add-container" style="display: none;">
  <div class="flex flex-col rounded-xl gap-4 px-8 py-5 fixed z-50 bg-white w-1/2 top-1/4 left-1/4">
    <h1 class="font-medium text-2xl">Add a new photo</h1>
    <%= form_with url: "/photos", model: @photo, class: "flex flex-col mt-4" do |form| %>
      <%= form.label :label, "Label", class: "mb-2", style: "color: #4F4F4F;" %>
      <%= form.text_field :label, class: "border rounded-xl p-4 border-gray-500", style: "filter: drop-shadow(0px 1px 6px rgba(0, 0, 0, 0.1));" %>
      <%= form.label :url, "Photo URL", class: "mt-6 mb-2", style: "color: #4F4F4F;" %>
      <%= form.text_field :url, class: "border rounded-xl p-4 border-gray-500", style: "filter: drop-shadow(0px 1px 6px rgba(0, 0, 0, 0.1));" %>

      <div class="flex flex-row-reverse gap-6 mt-6">
        <%= form.submit "Submit", class: "py-4 px-8 rounded-xl text-white font-bold text-base cursor-pointer", style: "background: #3DB46D;" %>
        <button id="cancel-add-modal" type="button" class="font-medium text-base" style="color: #BDBDBD;">Cancel</button>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/_delete_modal.html.erb
<div id="modal-delete-container" style="display: none;">
  <div class="flex flex-col rounded-xl gap-4 px-8 py-5 fixed z-50 bg-white w-1/2 top-1/4 left-1/4">
    <h1 class="font-medium text-2xl">Are you sure?</h1>
    <%= form_with method: :delete, class: "flex flex-col mt-4" do |form| %>
      <%= form.label :password, "Password", class: "mb-2", style: "color: #4F4F4F;" %>
      <%= form.password_field :password, class: "border rounded-xl p-4 border-gray-500", style: "filter: drop-shadow(0px 1px 6px rgba(0, 0, 0, 0.1));" %>

      <div class="flex flex-row-reverse gap-6 mt-6">
        <%= form.submit "Delete", class: "py-4 px-8 rounded-xl text-white font-bold text-base cursor-pointer", style: "background: #EB5757;" %>
        <button id="cancel-delete-modal" type="button" class="font-medium text-base" style="color: #BDBDBD;">Cancel</button>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/index.html.erb
<%= render 'add_modal' %>
<%= render 'delete_modal' %>

<div class="grid-content">
  <% @photos.each do |photo| %>
    <figure data-figure-id="<%= photo.id %>" style="flex-grow: <%= photo.width * 100 / photo.height.to_f %>; flex-basis: <%= photo.width * 240 / photo.height.to_f %>px;">
      <i style="padding-bottom: <%= photo.height / photo.width.to_f * 100.0 %>%;"></i>
      <img src="<%= photo.url %>" alt="<%= photo.label %>">
      <p class="figure-label" style="display: none;"><%= photo.label %></p>
      <button class="figure-button" style="display: none;">delete</button>
    </figure>
  <% end %>
</div>
<%= javascript_pack_tag 'photo', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="flex flex-row justify-between mt-8 mb-16 mx-24 pl-4 pr-4">
  <div class="flex flex-row gap-x-4">
    <%= link_to root_path, class: "flex" do %>
      <%= image_pack_tag 'my_unsplash_logo.svg' %>
    <% end %>
    <%= form_with url: search_photos_path, method: :get do |form| %>
      <div class="flex flex-row items-center gap-x-2 border-2 rounded-xl p-4">
        <span class="material-icons" style="color: #BDBDBD;">search</span>
        <%= form.text_field :query, placeholder: "Search by name" %>
      </div>
    <% end %>
  </div>
  <button id="add-photo" type="button" class="text-white font-bold py-4 px-6 rounded-xl" style="background-color: #3DB46D; box-shadow: 0px 1px 6px rgba(0, 0, 0, 0.1);">Add a photo</button>
</nav>